import "regenerator-runtime/runtime";

const template = document.createElement("template");
template.innerHTML = `
    <link href="suggestions.css" rel="stylesheet">
    <div class="wrapper">
        <input type="text" placeholder="Введите название, ИНН, ОГРН или адрес организации">
        <div class="suggestions"></div>
    </div>
`;

class InputSuggestions extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: "open" });
    this.shadowRoot.appendChild(template.content.cloneNode(true));
  }

  async getResults(query) {
    var url =
      "https://suggestions.dadata.ru/suggestions/api/4_1/rs/suggest/party";
    var token = "7c558dcad2e616f814b24147370300cde9d8c7cb";

    var options = {
      method: "POST",
      mode: "cors",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
        Authorization: "Token " + token,
      },
      body: JSON.stringify({ query: query }),
    };

    const data = await fetch(url, options);
    const json = await data.json();
    return json.suggestions;
  }

  async fetchSuggestions(e) {
    // var url =
    //   "https://suggestions.dadata.ru/suggestions/api/4_1/rs/suggest/party";
    // var token = "7c558dcad2e616f814b24147370300cde9d8c7cb";

    // var options = {
    //   method: "POST",
    //   mode: "cors",
    //   headers: {
    //     "Content-Type": "application/json",
    //     Accept: "application/json",
    //     Authorization: "Token " + token,
    //   },
    //   body: JSON.stringify({ query: e.target.value }),
    // };

    // const data = await fetch(url, options);
    // const json = await data.json();
    // const results = json.suggestions;
    const results = [
      {
        value: 'ООО "МОТОРИКА"',
        unrestricted_value: 'ООО "МОТОРИКА"',
        data: {
          kpp: "290101001",
          capital: null,
          management: {
            name: "Бределев Александр Николаевич",
            post: "ГЕНЕРАЛЬНЫЙ ДИРЕКТОР",
            disqualified: null,
          },
          founders: null,
          managers: null,
          predecessors: null,
          successors: null,
          branch_type: "MAIN",
          branch_count: 0,
          source: null,
          qc: null,
          hid: "48cb94246465dda592a5ea27967808e3d9760ae79ee8ae882199417aa84524c3",
          type: "LEGAL",
          state: {
            status: "ACTIVE",
            code: null,
            actuality_date: 1572393600000,
            registration_date: 1571356800000,
            liquidation_date: null,
          },
          opf: {
            type: "2014",
            code: "12300",
            full: "Общество с ограниченной ответственностью",
            short: "ООО",
          },
          name: {
            full_with_opf:
              'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МОТОРИКА"',
            short_with_opf: 'ООО "МОТОРИКА"',
            latin: null,
            full: "МОТОРИКА",
            short: "МОТОРИКА",
          },
          inn: "2901298957",
          ogrn: "1192901008717",
          okpo: "41899478",
          okato: "11401000000",
          oktmo: "11701000001",
          okogu: "4210014",
          okfs: "16",
          okved: "30.99",
          okveds: null,
          authorities: null,
          documents: null,
          licenses: null,
          finance: {
            tax_system: null,
            income: null,
            expense: null,
            debt: null,
            penalty: null,
            year: null,
          },
          address: {
            value: "г Архангельск, ул Коммунальная, д 6 стр 5",
            unrestricted_value:
              "163002, Архангельская обл, г Архангельск, ул Коммунальная, д 6 стр 5",
            data: {
              postal_code: "163002",
              country: "Россия",
              country_iso_code: "RU",
              federal_district: "Северо-Западный",
              region_fias_id: "294277aa-e25d-428c-95ad-46719c4ddb44",
              region_kladr_id: "2900000000000",
              region_iso_code: "RU-ARK",
              region_with_type: "Архангельская обл",
              region_type: "обл",
              region_type_full: "область",
              region: "Архангельская",
              area_fias_id: null,
              area_kladr_id: null,
              area_with_type: null,
              area_type: null,
              area_type_full: null,
              area: null,
              city_fias_id: "06814fb6-0dc3-4bec-ba20-11f894a0faf5",
              city_kladr_id: "2900000100000",
              city_with_type: "г Архангельск",
              city_type: "г",
              city_type_full: "город",
              city: "Архангельск",
              city_area: null,
              city_district_fias_id: null,
              city_district_kladr_id: null,
              city_district_with_type: null,
              city_district_type: null,
              city_district_type_full: null,
              city_district: null,
              settlement_fias_id: null,
              settlement_kladr_id: null,
              settlement_with_type: null,
              settlement_type: null,
              settlement_type_full: null,
              settlement: null,
              street_fias_id: "3a986f84-0d8c-44f1-8518-9e6b0f250073",
              street_kladr_id: "29000001000019300",
              street_with_type: "ул Коммунальная",
              street_type: "ул",
              street_type_full: "улица",
              street: "Коммунальная",
              stead_fias_id: null,
              stead_cadnum: null,
              stead_type: null,
              stead_type_full: null,
              stead: null,
              house_fias_id: "dc9133fb-152c-4f46-9870-557c61675ed3",
              house_kladr_id: "2900000100001930010",
              house_cadnum: null,
              house_type: "д",
              house_type_full: "дом",
              house: "6",
              block_type: "стр",
              block_type_full: "строение",
              block: "5",
              entrance: null,
              floor: null,
              flat_fias_id: null,
              flat_cadnum: null,
              flat_type: null,
              flat_type_full: null,
              flat: null,
              flat_area: null,
              square_meter_price: null,
              flat_price: null,
              postal_box: null,
              fias_id: "dc9133fb-152c-4f46-9870-557c61675ed3",
              fias_code: "29000001000000001930010",
              fias_level: "8",
              fias_actuality_state: "0",
              kladr_id: "2900000100001930010",
              geoname_id: "581049",
              capital_marker: "2",
              okato: "11401000000",
              oktmo: "11701000001",
              tax_office: "2901",
              tax_office_legal: "2901",
              timezone: "UTC+3",
              geo_lat: "64.5295688",
              geo_lon: "40.572254",
              beltway_hit: null,
              beltway_distance: null,
              metro: null,
              qc_geo: "1",
              qc_complete: null,
              qc_house: null,
              history_values: null,
              unparsed_parts: null,
              source:
                "163002, ОБЛАСТЬ АРХАНГЕЛЬСКАЯ, Г. АРХАНГЕЛЬСК, УЛ. КОММУНАЛЬНАЯ, Д. 6, СТР. 5",
              qc: "0",
            },
          },
          phones: null,
          emails: null,
          ogrn_date: 1571356800000,
          okved_type: "2014",
          employee_count: null,
        },
      },
      {
        value: 'ООО "МОТОРИКА"',
        unrestricted_value: 'ООО "МОТОРИКА"',
        data: {
          kpp: "402701001",
          capital: null,
          management: {
            name: "Алексеев Денис Сергеевич",
            post: "ДИРЕКТОР",
            disqualified: null,
          },
          founders: null,
          managers: null,
          predecessors: null,
          successors: null,
          branch_type: "MAIN",
          branch_count: 0,
          source: null,
          qc: null,
          hid: "29911a2e1e1f0261375d36633f801381fa665b8f091976939aa684c842e61b66",
          type: "LEGAL",
          state: {
            status: "ACTIVE",
            code: null,
            actuality_date: 1559606400000,
            registration_date: 1334880000000,
            liquidation_date: null,
          },
          opf: {
            type: "2014",
            code: "12300",
            full: "Общество с ограниченной ответственностью",
            short: "ООО",
          },
          name: {
            full_with_opf:
              'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МОТОРИКА"',
            short_with_opf: 'ООО "МОТОРИКА"',
            latin: null,
            full: "МОТОРИКА",
            short: "МОТОРИКА",
          },
          inn: "4028051108",
          ogrn: "1124028002273",
          okpo: "37833858",
          okato: "29401000000",
          oktmo: "29701000001",
          okogu: "4210014",
          okfs: "16",
          okved: "45.3",
          okveds: null,
          authorities: null,
          documents: null,
          licenses: null,
          finance: {
            tax_system: null,
            income: null,
            expense: null,
            debt: null,
            penalty: null,
            year: null,
          },
          address: {
            value: "г Калуга, ул Вишневского, д 17, кв 55",
            unrestricted_value:
              "248007, Калужская обл, г Калуга, ул Вишневского, д 17, кв 55",
            data: {
              postal_code: "248007",
              country: "Россия",
              country_iso_code: "RU",
              federal_district: "Центральный",
              region_fias_id: "18133adf-90c2-438e-88c4-62c41656de70",
              region_kladr_id: "4000000000000",
              region_iso_code: "RU-KLU",
              region_with_type: "Калужская обл",
              region_type: "обл",
              region_type_full: "область",
              region: "Калужская",
              area_fias_id: null,
              area_kladr_id: null,
              area_with_type: null,
              area_type: null,
              area_type_full: null,
              area: null,
              city_fias_id: "b502ae45-897e-4b6f-9776-6ff49740b537",
              city_kladr_id: "4000000100000",
              city_with_type: "г Калуга",
              city_type: "г",
              city_type_full: "город",
              city: "Калуга",
              city_area: null,
              city_district_fias_id: null,
              city_district_kladr_id: null,
              city_district_with_type: null,
              city_district_type: null,
              city_district_type_full: null,
              city_district: null,
              settlement_fias_id: null,
              settlement_kladr_id: null,
              settlement_with_type: null,
              settlement_type: null,
              settlement_type_full: null,
              settlement: null,
              street_fias_id: "3c8b076e-a3a9-49fc-be7b-42e46e673810",
              street_kladr_id: "40000001000005700",
              street_with_type: "ул Вишневского",
              street_type: "ул",
              street_type_full: "улица",
              street: "Вишневского",
              stead_fias_id: null,
              stead_cadnum: null,
              stead_type: null,
              stead_type_full: null,
              stead: null,
              house_fias_id: "4cd73f00-bb5b-4947-96aa-bf29bbe17ce2",
              house_kladr_id: "4000000100000570017",
              house_cadnum: null,
              house_type: "д",
              house_type_full: "дом",
              house: "17",
              block_type: null,
              block_type_full: null,
              block: null,
              entrance: null,
              floor: null,
              flat_fias_id: null,
              flat_cadnum: null,
              flat_type: "кв",
              flat_type_full: "квартира",
              flat: "55",
              flat_area: "34.8",
              square_meter_price: null,
              flat_price: null,
              postal_box: null,
              fias_id: "4cd73f00-bb5b-4947-96aa-bf29bbe17ce2",
              fias_code: "40000001000000000570017",
              fias_level: "8",
              fias_actuality_state: "0",
              kladr_id: "4000000100000570017",
              geoname_id: "553915",
              capital_marker: "2",
              okato: "29401000000",
              oktmo: "29701000001",
              tax_office: "4027",
              tax_office_legal: "4027",
              timezone: "UTC+3",
              geo_lat: "54.534225",
              geo_lon: "36.1665452",
              beltway_hit: null,
              beltway_distance: null,
              metro: null,
              qc_geo: "0",
              qc_complete: null,
              qc_house: null,
              history_values: null,
              unparsed_parts: null,
              source:
                "248007, ОБЛАСТЬ КАЛУЖСКАЯ, Г. КАЛУГА, УЛ. ВИШНЕВСКОГО, Д. 17, КВ. 55",
              qc: "0",
            },
          },
          phones: null,
          emails: null,
          ogrn_date: 1334880000000,
          okved_type: "2014",
          employee_count: null,
        },
      },
      {
        value: 'ООО "МОТОРИКА"',
        unrestricted_value: 'ООО "МОТОРИКА"',
        data: {
          kpp: "773101001",
          capital: null,
          management: {
            name: "Чех Илья Игоревич",
            post: "ГЕНЕРАЛЬНЫЙ ДИРЕКТОР",
            disqualified: null,
          },
          founders: null,
          managers: null,
          predecessors: null,
          successors: null,
          branch_type: "MAIN",
          branch_count: 0,
          source: null,
          qc: null,
          hid: "baf582914d601bc5246e881b07dfa6e336091a3857bebc3bf389aa0b4073223c",
          type: "LEGAL",
          state: {
            status: "ACTIVE",
            code: null,
            actuality_date: 1628121600000,
            registration_date: 1423094400000,
            liquidation_date: null,
          },
          opf: {
            type: "2014",
            code: "12300",
            full: "Общество с ограниченной ответственностью",
            short: "ООО",
          },
          name: {
            full_with_opf:
              'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МОТОРИКА"',
            short_with_opf: 'ООО "МОТОРИКА"',
            latin: null,
            full: "МОТОРИКА",
            short: "МОТОРИКА",
          },
          inn: "7719402047",
          ogrn: "1157746078984",
          okpo: "27539247",
          okato: "45268569000",
          oktmo: "45321000000",
          okogu: "4210011",
          okfs: "34",
          okved: "72.19",
          okveds: null,
          authorities: null,
          documents: null,
          licenses: null,
          finance: {
            tax_system: null,
            income: null,
            expense: null,
            debt: null,
            penalty: null,
            year: null,
          },
          address: {
            value:
              "121205, ГОРОД МОСКВА, ТЕР СКОЛКОВО ИННОВАЦИОННОГО ЦЕНТРА, Б-Р БОЛЬШОЙ, Д. 42, СТР. 1, ЭТ 1 ПОМ 334 РАБ 10",
            unrestricted_value:
              "121205, ГОРОД МОСКВА, ТЕР СКОЛКОВО ИННОВАЦИОННОГО ЦЕНТРА, Б-Р БОЛЬШОЙ, Д. 42, СТР. 1, ЭТ 1 ПОМ 334 РАБ 10",
            data: {
              postal_code: "121205",
              country: "Россия",
              country_iso_code: "RU",
              federal_district: "Центральный",
              region_fias_id: "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
              region_kladr_id: "7700000000000",
              region_iso_code: "RU-MOW",
              region_with_type: "г Москва",
              region_type: "г",
              region_type_full: "город",
              region: "Москва",
              area_fias_id: null,
              area_kladr_id: null,
              area_with_type: null,
              area_type: null,
              area_type_full: null,
              area: null,
              city_fias_id: "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
              city_kladr_id: "7700000000000",
              city_with_type: "г Москва",
              city_type: "г",
              city_type_full: "город",
              city: "Москва",
              city_area: "Западный",
              city_district_fias_id: null,
              city_district_kladr_id: null,
              city_district_with_type: "Можайский р-н",
              city_district_type: "р-н",
              city_district_type_full: "район",
              city_district: "Можайский",
              settlement_fias_id: "db22b565-f8ab-464b-b76f-1106629e9e95",
              settlement_kladr_id: "7700000043000",
              settlement_with_type: "тер Сколково инновационного центра",
              settlement_type: "тер",
              settlement_type_full: "территория",
              settlement: "Сколково инновационного центра",
              street_fias_id: "5a08abaa-929f-4855-a460-c691f37b5a25",
              street_kladr_id: "77000000430000400",
              street_with_type: "Большой б-р",
              street_type: "б-р",
              street_type_full: "бульвар",
              street: "Большой",
              stead_fias_id: null,
              stead_cadnum: null,
              stead_type: null,
              stead_type_full: null,
              stead: null,
              house_fias_id: "0519d3e3-d0f6-4106-b1af-c14ddf8f43f5",
              house_kladr_id: "7700000043000040007",
              house_cadnum: null,
              house_type: "д",
              house_type_full: "дом",
              house: "42",
              block_type: "стр",
              block_type_full: "строение",
              block: "1",
              entrance: null,
              floor: "1",
              flat_fias_id: null,
              flat_cadnum: null,
              flat_type: "помещ",
              flat_type_full: "помещение",
              flat: "334",
              flat_area: null,
              square_meter_price: null,
              flat_price: null,
              postal_box: null,
              fias_id: "0519d3e3-d0f6-4106-b1af-c14ddf8f43f5",
              fias_code: "77000000430000000040007",
              fias_level: "8",
              fias_actuality_state: "0",
              kladr_id: "7700000043000040007",
              geoname_id: "524901",
              capital_marker: "0",
              okato: "45268569000",
              oktmo: "45321000",
              tax_office: "7731",
              tax_office_legal: "7731",
              timezone: "UTC+3",
              geo_lat: "55.6921337",
              geo_lon: "37.3474933",
              beltway_hit: "OUT_MKAD",
              beltway_distance: "4",
              metro: [
                {
                  name: "Сколково",
                  line: "Белорусско-Савеловский",
                  distance: 0.9,
                },
                {
                  name: "Баковка",
                  line: "Белорусско-Савеловский",
                  distance: 2.3,
                },
                {
                  name: "Немчиновка",
                  line: "Белорусско-Савеловский",
                  distance: 3.2,
                },
              ],
              qc_geo: "0",
              qc_complete: null,
              qc_house: null,
              history_values: null,
              unparsed_parts: null,
              source:
                "121205, ГОРОД МОСКВА, ТЕР СКОЛКОВО ИННОВАЦИОННОГО ЦЕНТРА, Б-Р БОЛЬШОЙ, Д. 42, СТР. 1, ЭТ 1 ПОМ 334 РАБ 10",
              qc: "1",
            },
          },
          phones: null,
          emails: null,
          ogrn_date: 1423094400000,
          okved_type: "2014",
          employee_count: null,
        },
      },
      {
        value: 'ООО "МОТОРИКА"',
        unrestricted_value: 'ООО "МОТОРИКА"',
        data: {
          kpp: "526201001",
          capital: null,
          management: {
            name: "Снегуренко Евгений Алексеевич",
            post: "ГЕНЕРАЛЬНЫЙ ДИРЕКТОР",
            disqualified: null,
          },
          founders: null,
          managers: null,
          predecessors: null,
          successors: null,
          branch_type: "MAIN",
          branch_count: 0,
          source: null,
          qc: null,
          hid: "5b1bbf0bf10088dab2140cfd02987abb5116cef5828de47016456054840f47be",
          type: "LEGAL",
          state: {
            status: "ACTIVE",
            code: null,
            actuality_date: 1502409600000,
            registration_date: 1436745600000,
            liquidation_date: null,
          },
          opf: {
            type: "2014",
            code: "12300",
            full: "Общество с ограниченной ответственностью",
            short: "ООО",
          },
          name: {
            full_with_opf:
              'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МОТОРИКА"',
            short_with_opf: 'ООО "МОТОРИКА"',
            latin: null,
            full: "МОТОРИКА",
            short: "МОТОРИКА",
          },
          inn: "5262321353",
          ogrn: "1155262009561",
          okpo: "50333681",
          okato: "22401379000",
          oktmo: "22701000001",
          okogu: "4210014",
          okfs: "16",
          okved: "73.11",
          okveds: null,
          authorities: null,
          documents: null,
          licenses: null,
          finance: {
            tax_system: null,
            income: null,
            expense: null,
            debt: null,
            penalty: null,
            year: null,
          },
          address: {
            value: "г Нижний Новгород, ул Нартова, д 6, кв 5",
            unrestricted_value:
              "603081, Нижегородская обл, г Нижний Новгород, Советский р-н, ул Нартова, д 6, кв 5",
            data: {
              postal_code: "603081",
              country: "Россия",
              country_iso_code: "RU",
              federal_district: "Приволжский",
              region_fias_id: "88cd27e2-6a8a-4421-9718-719a28a0a088",
              region_kladr_id: "5200000000000",
              region_iso_code: "RU-NIZ",
              region_with_type: "Нижегородская обл",
              region_type: "обл",
              region_type_full: "область",
              region: "Нижегородская",
              area_fias_id: null,
              area_kladr_id: null,
              area_with_type: null,
              area_type: null,
              area_type_full: null,
              area: null,
              city_fias_id: "555e7d61-d9a7-4ba6-9770-6caa8198c483",
              city_kladr_id: "5200000100000",
              city_with_type: "г Нижний Новгород",
              city_type: "г",
              city_type_full: "город",
              city: "Нижний Новгород",
              city_area: null,
              city_district_fias_id: null,
              city_district_kladr_id: null,
              city_district_with_type: "Советский р-н",
              city_district_type: "р-н",
              city_district_type_full: "район",
              city_district: "Советский",
              settlement_fias_id: null,
              settlement_kladr_id: null,
              settlement_with_type: null,
              settlement_type: null,
              settlement_type_full: null,
              settlement: null,
              street_fias_id: "c69b5f1e-7fe9-43d4-b478-b523e22a0373",
              street_kladr_id: "52000001000071500",
              street_with_type: "ул Нартова",
              street_type: "ул",
              street_type_full: "улица",
              street: "Нартова",
              stead_fias_id: null,
              stead_cadnum: null,
              stead_type: null,
              stead_type_full: null,
              stead: null,
              house_fias_id: "c38269c0-767d-4c6b-822f-8d4b0b284027",
              house_kladr_id: "5200000100007150025",
              house_cadnum: null,
              house_type: "д",
              house_type_full: "дом",
              house: "6",
              block_type: null,
              block_type_full: null,
              block: null,
              entrance: null,
              floor: null,
              flat_fias_id: null,
              flat_cadnum: null,
              flat_type: "кв",
              flat_type_full: "квартира",
              flat: "5",
              flat_area: null,
              square_meter_price: null,
              flat_price: null,
              postal_box: null,
              fias_id: "c38269c0-767d-4c6b-822f-8d4b0b284027",
              fias_code: "52000001000000007150025",
              fias_level: "8",
              fias_actuality_state: "0",
              kladr_id: "5200000100007150025",
              geoname_id: "520555",
              capital_marker: "2",
              okato: "22401379000",
              oktmo: "22701000001",
              tax_office: "5262",
              tax_office_legal: "5262",
              timezone: "UTC+3",
              geo_lat: "56.2824655",
              geo_lon: "43.9954163",
              beltway_hit: null,
              beltway_distance: null,
              metro: [
                { name: "Горьковская", line: "Автозаводская", distance: 3.5 },
                { name: "Ленинская", line: "Автозаводская", distance: 4.0 },
                { name: "Заречная", line: "Автозаводская", distance: 4.2 },
              ],
              qc_geo: "0",
              qc_complete: null,
              qc_house: null,
              history_values: null,
              unparsed_parts: null,
              source:
                "603104, ОБЛАСТЬ НИЖЕГОРОДСКАЯ, Г. НИЖНИЙ НОВГОРОД, УЛ. НАРТОВА, Д. 6, К. 5, ОФИС 12",
              qc: "0",
            },
          },
          phones: null,
          emails: null,
          ogrn_date: 1436745600000,
          okved_type: "2014",
          employee_count: null,
        },
      },
      {
        value: 'ООО "МОТОРИКА"',
        unrestricted_value: 'ООО "МОТОРИКА"',
        data: {
          kpp: "631801001",
          capital: null,
          management: {
            name: "Сладков Роман Николаевич",
            post: "ДИРЕКТОР",
            disqualified: null,
          },
          founders: null,
          managers: null,
          predecessors: null,
          successors: null,
          branch_type: "MAIN",
          branch_count: 0,
          source: null,
          qc: null,
          hid: "799a54dcee1652b275f1e75f00e1fb9b8a818b4c3822972a33ee84c3cadec5e2",
          type: "LEGAL",
          state: {
            status: "ACTIVE",
            code: null,
            actuality_date: 1602547200000,
            registration_date: 1423180800000,
            liquidation_date: null,
          },
          opf: {
            type: "2014",
            code: "12300",
            full: "Общество с ограниченной ответственностью",
            short: "ООО",
          },
          name: {
            full_with_opf:
              'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МОТОРИКА"',
            short_with_opf: 'ООО "МОТОРИКА"',
            latin: null,
            full: "МОТОРИКА",
            short: "МОТОРИКА",
          },
          inn: "6318002113",
          ogrn: "1156318001058",
          okpo: "40962051",
          okato: "36401392000",
          oktmo: "36701345000",
          okogu: "4210014",
          okfs: "16",
          okved: "45.40.2",
          okveds: null,
          authorities: null,
          documents: null,
          licenses: null,
          finance: {
            tax_system: null,
            income: null,
            expense: null,
            debt: null,
            penalty: null,
            year: null,
          },
          address: {
            value:
              "443017, ОБЛАСТЬ САМАРСКАЯ, Г. САМАРА, Ш. ЗАВОДСКОЕ, Д. 13А, ЛИТЕР АА1А2А3",
            unrestricted_value:
              "443017, ОБЛАСТЬ САМАРСКАЯ, Г. САМАРА, Ш. ЗАВОДСКОЕ, Д. 13А, ЛИТЕР АА1А2А3",
            data: {
              postal_code: "443022",
              country: "Россия",
              country_iso_code: "RU",
              federal_district: "Приволжский",
              region_fias_id: "df3d7359-afa9-4aaa-8ff9-197e73906b1c",
              region_kladr_id: "6300000000000",
              region_iso_code: "RU-SAM",
              region_with_type: "Самарская обл",
              region_type: "обл",
              region_type_full: "область",
              region: "Самарская",
              area_fias_id: null,
              area_kladr_id: null,
              area_with_type: null,
              area_type: null,
              area_type_full: null,
              area: null,
              city_fias_id: "bb035cc3-1dc2-4627-9d25-a1bf2d4b936b",
              city_kladr_id: "6300000100000",
              city_with_type: "г Самара",
              city_type: "г",
              city_type_full: "город",
              city: "Самара",
              city_area: null,
              city_district_fias_id: null,
              city_district_kladr_id: null,
              city_district_with_type: "Советский р-н",
              city_district_type: "р-н",
              city_district_type_full: "район",
              city_district: "Советский",
              settlement_fias_id: null,
              settlement_kladr_id: null,
              settlement_with_type: null,
              settlement_type: null,
              settlement_type_full: null,
              settlement: null,
              street_fias_id: "099e7974-8798-4107-a71f-4511d724138f",
              street_kladr_id: "63000001000085500",
              street_with_type: "Заводское шоссе",
              street_type: "ш",
              street_type_full: "шоссе",
              street: "Заводское",
              stead_fias_id: null,
              stead_cadnum: null,
              stead_type: null,
              stead_type_full: null,
              stead: null,
              house_fias_id: null,
              house_kladr_id: null,
              house_cadnum: null,
              house_type: "д",
              house_type_full: "дом",
              house: "13А",
              block_type: "стр",
              block_type_full: "строение",
              block: "аа",
              entrance: null,
              floor: null,
              flat_fias_id: null,
              flat_cadnum: null,
              flat_type: null,
              flat_type_full: null,
              flat: null,
              flat_area: null,
              square_meter_price: null,
              flat_price: null,
              postal_box: null,
              fias_id: "099e7974-8798-4107-a71f-4511d724138f",
              fias_code: "63000001000000008550000",
              fias_level: "7",
              fias_actuality_state: "0",
              kladr_id: "63000001000085500",
              geoname_id: "499099",
              capital_marker: "2",
              okato: "36401392000",
              oktmo: "36701345",
              tax_office: "6318",
              tax_office_legal: "6318",
              timezone: "UTC+4",
              geo_lat: "53.1811884",
              geo_lon: "50.2137364",
              beltway_hit: null,
              beltway_distance: null,
              metro: [
                { name: "Советская", line: "Первая", distance: 2.3 },
                { name: "Спортивная", line: "Первая", distance: 2.4 },
                { name: "Гагаринская", line: "Первая", distance: 3.3 },
              ],
              qc_geo: "1",
              qc_complete: null,
              qc_house: null,
              history_values: null,
              unparsed_parts: null,
              source:
                "443017, ОБЛАСТЬ САМАРСКАЯ, Г. САМАРА, Ш. ЗАВОДСКОЕ, Д. 13А, ЛИТЕР АА1А2А3",
              qc: "1",
            },
          },
          phones: null,
          emails: null,
          ogrn_date: 1423180800000,
          okved_type: "2014",
          employee_count: null,
        },
      },
      {
        value: 'ООО "МОТОРИКА"',
        unrestricted_value: 'ООО "МОТОРИКА"',
        data: {
          kpp: "667801001",
          capital: null,
          management: {
            name: "Арсентьева Алла Юрьевна",
            post: "ДИРЕКТОР",
            disqualified: null,
          },
          founders: null,
          managers: null,
          predecessors: null,
          successors: null,
          branch_type: "MAIN",
          branch_count: 0,
          source: null,
          qc: null,
          hid: "c8629a69eef93b52a80183b9786c08f939879b95efcbd0b7b41f98e3ac65a78f",
          type: "LEGAL",
          state: {
            status: "ACTIVE",
            code: null,
            actuality_date: 1605744000000,
            registration_date: 1367798400000,
            liquidation_date: null,
          },
          opf: {
            type: "2014",
            code: "12300",
            full: "Общество с ограниченной ответственностью",
            short: "ООО",
          },
          name: {
            full_with_opf:
              'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МОТОРИКА"',
            short_with_opf: 'ООО "МОТОРИКА"',
            latin: null,
            full: "МОТОРИКА",
            short: "МОТОРИКА",
          },
          inn: "6678029047",
          ogrn: "1136678006706",
          okpo: "25078598",
          okato: "65412000007",
          oktmo: "65731000136",
          okogu: "4210014",
          okfs: "16",
          okved: "52.29",
          okveds: null,
          authorities: null,
          documents: null,
          licenses: null,
          finance: {
            tax_system: null,
            income: null,
            expense: null,
            debt: null,
            penalty: null,
            year: null,
          },
          address: {
            value:
              "Свердловская обл, г Березовский, поселок Лосиный, ул Октябрьская, стр 6, офис 3",
            unrestricted_value:
              "623710, Свердловская обл, г Березовский, поселок Лосиный, ул Октябрьская, стр 6, офис 3",
            data: {
              postal_code: "623710",
              country: "Россия",
              country_iso_code: "RU",
              federal_district: "Уральский",
              region_fias_id: "92b30014-4d52-4e2e-892d-928142b924bf",
              region_kladr_id: "6600000000000",
              region_iso_code: "RU-SVE",
              region_with_type: "Свердловская обл",
              region_type: "обл",
              region_type_full: "область",
              region: "Свердловская",
              area_fias_id: null,
              area_kladr_id: null,
              area_with_type: null,
              area_type: null,
              area_type_full: null,
              area: null,
              city_fias_id: "adf5df2b-2c2e-45a9-b971-05550353cf43",
              city_kladr_id: "6600000300000",
              city_with_type: "г Березовский",
              city_type: "г",
              city_type_full: "город",
              city: "Березовский",
              city_area: null,
              city_district_fias_id: null,
              city_district_kladr_id: null,
              city_district_with_type: null,
              city_district_type: null,
              city_district_type_full: null,
              city_district: null,
              settlement_fias_id: "17904e21-bee0-4722-8959-f7fe35c4636f",
              settlement_kladr_id: "6600000300900",
              settlement_with_type: "поселок Лосиный",
              settlement_type: "п",
              settlement_type_full: "поселок",
              settlement: "Лосиный",
              street_fias_id: "c2090ccc-7b8d-4aa7-983d-6529920c5a63",
              street_kladr_id: "66000003009000800",
              street_with_type: "ул Октябрьская",
              street_type: "ул",
              street_type_full: "улица",
              street: "Октябрьская",
              stead_fias_id: null,
              stead_cadnum: null,
              stead_type: null,
              stead_type_full: null,
              stead: null,
              house_fias_id: "1633552e-980a-45d1-a2c4-d1e45c66394e",
              house_kladr_id: "6600000300900080016",
              house_cadnum: null,
              house_type: "стр",
              house_type_full: "строение",
              house: "6",
              block_type: null,
              block_type_full: null,
              block: null,
              entrance: null,
              floor: null,
              flat_fias_id: null,
              flat_cadnum: null,
              flat_type: "офис",
              flat_type_full: "офис",
              flat: "3",
              flat_area: null,
              square_meter_price: null,
              flat_price: null,
              postal_box: null,
              fias_id: "1633552e-980a-45d1-a2c4-d1e45c66394e",
              fias_code: "66000003009000000080016",
              fias_level: "8",
              fias_actuality_state: "0",
              kladr_id: "6600000300900080016",
              geoname_id: "1510203",
              capital_marker: "0",
              okato: "65412000007",
              oktmo: "65731000136",
              tax_office: "6678",
              tax_office_legal: "6678",
              timezone: "UTC+5",
              geo_lat: "57.138429",
              geo_lon: "61.0725829",
              beltway_hit: null,
              beltway_distance: null,
              metro: null,
              qc_geo: "2",
              qc_complete: null,
              qc_house: null,
              history_values: null,
              unparsed_parts: null,
              source:
                "623710, ОБЛАСТЬ СВЕРДЛОВСКАЯ, Г. БЕРЕЗОВСКИЙ, П ЛОСИНЫЙ, УЛ. ОКТЯБРЬСКАЯ, СТР. 6, ОФИС 3",
              qc: "0",
            },
          },
          phones: null,
          emails: null,
          ogrn_date: 1367798400000,
          okved_type: "2014",
          employee_count: null,
        },
      },
      {
        value: 'ООО "МОТОРИКА"',
        unrestricted_value: 'ООО "МОТОРИКА"',
        data: {
          kpp: "720301001",
          capital: null,
          management: {
            name: "Рябова Мария Васильевна",
            post: "ДИРЕКТОР",
            disqualified: null,
          },
          founders: null,
          managers: null,
          predecessors: null,
          successors: null,
          branch_type: "MAIN",
          branch_count: 0,
          source: null,
          qc: null,
          hid: "7bfa27fe9902aebaea21938e9395b122071e1f5b842ff15e4024523f22cb3d21",
          type: "LEGAL",
          state: {
            status: "ACTIVE",
            code: null,
            actuality_date: 1640995200000,
            registration_date: 1172448000000,
            liquidation_date: null,
          },
          opf: {
            type: "2014",
            code: "12300",
            full: "Общество с ограниченной ответственностью",
            short: "ООО",
          },
          name: {
            full_with_opf:
              'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МОТОРИКА"',
            short_with_opf: 'ООО "МОТОРИКА"',
            latin: null,
            full: "МОТОРИКА",
            short: "МОТОРИКА",
          },
          inn: "7203190416",
          ogrn: "1077203011115",
          okpo: "98784938",
          okato: "71401368000",
          oktmo: "71701000001",
          okogu: "4210014",
          okfs: "16",
          okved: "42.22",
          okveds: null,
          authorities: null,
          documents: null,
          licenses: null,
          finance: {
            tax_system: null,
            income: null,
            expense: null,
            debt: null,
            penalty: null,
            year: null,
          },
          address: {
            value: "г Тюмень, ул Дамбовская, д 10",
            unrestricted_value:
              "625034, Тюменская обл, г Тюмень, ул Дамбовская, д 10",
            data: {
              postal_code: "625034",
              country: "Россия",
              country_iso_code: "RU",
              federal_district: "Уральский",
              region_fias_id: "54049357-326d-4b8f-b224-3c6dc25d6dd3",
              region_kladr_id: "7200000000000",
              region_iso_code: "RU-TYU",
              region_with_type: "Тюменская обл",
              region_type: "обл",
              region_type_full: "область",
              region: "Тюменская",
              area_fias_id: null,
              area_kladr_id: null,
              area_with_type: null,
              area_type: null,
              area_type_full: null,
              area: null,
              city_fias_id: "9ae64229-9f7b-4149-b27a-d1f6ec74b5ce",
              city_kladr_id: "7200000100000",
              city_with_type: "г Тюмень",
              city_type: "г",
              city_type_full: "город",
              city: "Тюмень",
              city_area: null,
              city_district_fias_id: null,
              city_district_kladr_id: null,
              city_district_with_type: null,
              city_district_type: null,
              city_district_type_full: null,
              city_district: null,
              settlement_fias_id: null,
              settlement_kladr_id: null,
              settlement_with_type: null,
              settlement_type: null,
              settlement_type_full: null,
              settlement: null,
              street_fias_id: "d5ddd9c2-0ebf-4987-aed5-358fc60db06f",
              street_kladr_id: "72000001000025900",
              street_with_type: "ул Дамбовская",
              street_type: "ул",
              street_type_full: "улица",
              street: "Дамбовская",
              stead_fias_id: null,
              stead_cadnum: null,
              stead_type: null,
              stead_type_full: null,
              stead: null,
              house_fias_id: "72e17407-8f3e-41c5-9cbd-edf3b1f63a0b",
              house_kladr_id: "7200000100002590031",
              house_cadnum: null,
              house_type: "д",
              house_type_full: "дом",
              house: "10",
              block_type: null,
              block_type_full: null,
              block: null,
              entrance: null,
              floor: null,
              flat_fias_id: null,
              flat_cadnum: null,
              flat_type: null,
              flat_type_full: null,
              flat: null,
              flat_area: "446.0",
              square_meter_price: null,
              flat_price: null,
              postal_box: null,
              fias_id: "72e17407-8f3e-41c5-9cbd-edf3b1f63a0b",
              fias_code: "72000001000000002590031",
              fias_level: "8",
              fias_actuality_state: "0",
              kladr_id: "7200000100002590031",
              geoname_id: "1488754",
              capital_marker: "2",
              okato: "71401000000",
              oktmo: "71701000001",
              tax_office: "7230",
              tax_office_legal: "7203",
              timezone: "UTC+5",
              geo_lat: "57.1529173",
              geo_lon: "65.6099649",
              beltway_hit: null,
              beltway_distance: null,
              metro: null,
              qc_geo: "0",
              qc_complete: null,
              qc_house: null,
              history_values: null,
              unparsed_parts: null,
              source:
                "625039, ОБЛАСТЬ ТЮМЕНСКАЯ, Г. ТЮМЕНЬ, УЛ. ДАМБОВСКАЯ, Д.10, -, -",
              qc: "0",
            },
          },
          phones: null,
          emails: null,
          ogrn_date: 1172448000000,
          okved_type: "2014",
          employee_count: null,
        },
      },
      {
        value: 'ООО "МОТОРИКА"',
        unrestricted_value: 'ООО "МОТОРИКА"',
        data: {
          kpp: "720301001",
          capital: null,
          management: {
            name: "Никифоров Павел Владимирович",
            post: "ГЕНЕРАЛЬНЫЙ ДИРЕКТОР",
            disqualified: null,
          },
          founders: null,
          managers: null,
          predecessors: null,
          successors: null,
          branch_type: "MAIN",
          branch_count: 0,
          source: null,
          qc: null,
          hid: "0321847a77de25e03df98cc05f0ed24a34a6e4de02b345d1e29a2e1634bc4d51",
          type: "LEGAL",
          state: {
            status: "ACTIVE",
            code: null,
            actuality_date: 1542067200000,
            registration_date: 1541721600000,
            liquidation_date: null,
          },
          opf: {
            type: "2014",
            code: "12300",
            full: "Общество с ограниченной ответственностью",
            short: "ООО",
          },
          name: {
            full_with_opf:
              'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МОТОРИКА"',
            short_with_opf: 'ООО "МОТОРИКА"',
            latin: null,
            full: "МОТОРИКА",
            short: "МОТОРИКА",
          },
          inn: "7203462155",
          ogrn: "1187232027564",
          okpo: "34086315",
          okato: "71401372000",
          oktmo: "71701000001",
          okogu: "4210014",
          okfs: "16",
          okved: "45.40",
          okveds: null,
          authorities: null,
          documents: null,
          licenses: null,
          finance: {
            tax_system: null,
            income: null,
            expense: null,
            debt: null,
            penalty: null,
            year: null,
          },
          address: {
            value: "г Тюмень, ул Попова, д 7, кв 78",
            unrestricted_value:
              "625048, Тюменская обл, г Тюмень, ул Попова, д 7, кв 78",
            data: {
              postal_code: "625048",
              country: "Россия",
              country_iso_code: "RU",
              federal_district: "Уральский",
              region_fias_id: "54049357-326d-4b8f-b224-3c6dc25d6dd3",
              region_kladr_id: "7200000000000",
              region_iso_code: "RU-TYU",
              region_with_type: "Тюменская обл",
              region_type: "обл",
              region_type_full: "область",
              region: "Тюменская",
              area_fias_id: null,
              area_kladr_id: null,
              area_with_type: null,
              area_type: null,
              area_type_full: null,
              area: null,
              city_fias_id: "9ae64229-9f7b-4149-b27a-d1f6ec74b5ce",
              city_kladr_id: "7200000100000",
              city_with_type: "г Тюмень",
              city_type: "г",
              city_type_full: "город",
              city: "Тюмень",
              city_area: null,
              city_district_fias_id: null,
              city_district_kladr_id: null,
              city_district_with_type: null,
              city_district_type: null,
              city_district_type_full: null,
              city_district: null,
              settlement_fias_id: null,
              settlement_kladr_id: null,
              settlement_with_type: null,
              settlement_type: null,
              settlement_type_full: null,
              settlement: null,
              street_fias_id: "838b9d67-ddbc-40d7-9f30-79db31fd7988",
              street_kladr_id: "72000001000015100",
              street_with_type: "ул Попова",
              street_type: "ул",
              street_type_full: "улица",
              street: "Попова",
              stead_fias_id: null,
              stead_cadnum: null,
              stead_type: null,
              stead_type_full: null,
              stead: null,
              house_fias_id: "e82ace85-9b3d-4356-a185-fab7c2757c29",
              house_kladr_id: "7200000100001510017",
              house_cadnum: null,
              house_type: "д",
              house_type_full: "дом",
              house: "7",
              block_type: null,
              block_type_full: null,
              block: null,
              entrance: null,
              floor: null,
              flat_fias_id: null,
              flat_cadnum: null,
              flat_type: "кв",
              flat_type_full: "квартира",
              flat: "78",
              flat_area: "63.7",
              square_meter_price: "64937",
              flat_price: "4136487",
              postal_box: null,
              fias_id: "e82ace85-9b3d-4356-a185-fab7c2757c29",
              fias_code: "72000001000000001510017",
              fias_level: "8",
              fias_actuality_state: "0",
              kladr_id: "7200000100001510017",
              geoname_id: "1488754",
              capital_marker: "2",
              okato: "71401000000",
              oktmo: "71701000001",
              tax_office: "7230",
              tax_office_legal: "7203",
              timezone: "UTC+5",
              geo_lat: "57.1431044",
              geo_lon: "65.5427791",
              beltway_hit: null,
              beltway_distance: null,
              metro: null,
              qc_geo: "0",
              qc_complete: null,
              qc_house: null,
              history_values: null,
              unparsed_parts: null,
              source:
                "625048, ОБЛАСТЬ ТЮМЕНСКАЯ, Г. ТЮМЕНЬ, УЛ. ПОПОВА, Д. 7, КВ. 78",
              qc: "0",
            },
          },
          phones: null,
          emails: null,
          ogrn_date: 1541721600000,
          okved_type: "2014",
          employee_count: null,
        },
      },
      {
        value: 'ООО "МОТОРИКА"',
        unrestricted_value: 'ООО "МОТОРИКА"',
        data: {
          kpp: "731001001",
          capital: null,
          management: {
            name: "Мазавин Алексей Владимирович",
            post: "ГЕНЕРАЛЬНЫЙ ДИРЕКТОР",
            disqualified: null,
          },
          founders: null,
          managers: null,
          predecessors: null,
          successors: null,
          branch_type: "MAIN",
          branch_count: 0,
          source: null,
          qc: null,
          hid: "0a487e33550bfb31a5dfcedb2a1bf8ec165838bf12dbeb6d619043fc13bec65b",
          type: "LEGAL",
          state: {
            status: "ACTIVE",
            code: null,
            actuality_date: 1614816000000,
            registration_date: 1060905600000,
            liquidation_date: null,
          },
          opf: {
            type: "2014",
            code: "12300",
            full: "Общество с ограниченной ответственностью",
            short: "ООО",
          },
          name: {
            full_with_opf:
              'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МОТОРИКА"',
            short_with_opf: 'ООО "МОТОРИКА"',
            latin: null,
            full: "МОТОРИКА",
            short: "МОТОРИКА",
          },
          inn: "7310008820",
          ogrn: "1037300460823",
          okpo: "25449793",
          okato: "73222560000",
          oktmo: "73622160051",
          okogu: "4210014",
          okfs: "16",
          okved: "29.31",
          okveds: null,
          authorities: null,
          documents: null,
          licenses: null,
          finance: {
            tax_system: null,
            income: null,
            expense: null,
            debt: null,
            penalty: null,
            year: null,
          },
          address: {
            value:
              "Ульяновская обл, Мелекесский р-н, рп Новая Майна, ул Спортивная, зд 10",
            unrestricted_value:
              "433556, Ульяновская обл, Мелекесский р-н, рп Новая Майна, ул Спортивная, зд 10",
            data: {
              postal_code: "433556",
              country: "Россия",
              country_iso_code: "RU",
              federal_district: "Приволжский",
              region_fias_id: "fee76045-fe22-43a4-ad58-ad99e903bd58",
              region_kladr_id: "7300000000000",
              region_iso_code: "RU-ULY",
              region_with_type: "Ульяновская обл",
              region_type: "обл",
              region_type_full: "область",
              region: "Ульяновская",
              area_fias_id: "214a98f4-bd25-402b-9876-ce91d69b70a2",
              area_kladr_id: "7300900000000",
              area_with_type: "Мелекесский р-н",
              area_type: "р-н",
              area_type_full: "район",
              area: "Мелекесский",
              city_fias_id: null,
              city_kladr_id: null,
              city_with_type: null,
              city_type: null,
              city_type_full: null,
              city: null,
              city_area: null,
              city_district_fias_id: null,
              city_district_kladr_id: null,
              city_district_with_type: null,
              city_district_type: null,
              city_district_type_full: null,
              city_district: null,
              settlement_fias_id: "2c462b9b-7558-4166-9c1a-48a97e1a83d0",
              settlement_kladr_id: "7300900001600",
              settlement_with_type: "рп Новая Майна",
              settlement_type: "рп",
              settlement_type_full: "рабочий поселок",
              settlement: "Новая Майна",
              street_fias_id: "f0b5f1d2-e936-4352-a218-19beb8e664fe",
              street_kladr_id: "73009000016003600",
              street_with_type: "ул Спортивная",
              street_type: "ул",
              street_type_full: "улица",
              street: "Спортивная",
              stead_fias_id: null,
              stead_cadnum: null,
              stead_type: null,
              stead_type_full: null,
              stead: null,
              house_fias_id: "1253dd70-bc1a-45f0-8430-67e19469eaec",
              house_kladr_id: "7300900001600360010",
              house_cadnum: null,
              house_type: "зд",
              house_type_full: "здание",
              house: "10",
              block_type: null,
              block_type_full: null,
              block: null,
              entrance: null,
              floor: null,
              flat_fias_id: null,
              flat_cadnum: null,
              flat_type: null,
              flat_type_full: null,
              flat: null,
              flat_area: null,
              square_meter_price: null,
              flat_price: null,
              postal_box: null,
              fias_id: "1253dd70-bc1a-45f0-8430-67e19469eaec",
              fias_code: "73009000016000000360010",
              fias_level: "8",
              fias_actuality_state: "0",
              kladr_id: "7300900001600360010",
              geoname_id: "479119",
              capital_marker: "0",
              okato: "73222560000",
              oktmo: "73622160051",
              tax_office: "7329",
              tax_office_legal: "7329",
              timezone: "UTC+4",
              geo_lat: "54.1553108",
              geo_lon: "49.7554759",
              beltway_hit: null,
              beltway_distance: null,
              metro: null,
              qc_geo: "2",
              qc_complete: null,
              qc_house: null,
              history_values: null,
              unparsed_parts: null,
              source:
                "433556, ОБЛАСТЬ УЛЬЯНОВСКАЯ, Р-Н МЕЛЕКЕССКИЙ, РП НОВАЯ МАЙНА, УЛ. СПОРТИВНАЯ, Д.10",
              qc: "0",
            },
          },
          phones: null,
          emails: null,
          ogrn_date: 1060905600000,
          okved_type: "2014",
          employee_count: null,
        },
      },
      {
        value: 'ООО "ИЦ МОТОРИКА"',
        unrestricted_value: 'ООО "ИЦ МОТОРИКА"',
        data: {
          kpp: "773101001",
          capital: null,
          management: {
            name: "Чех Илья Игоревич",
            post: "ГЕНЕРАЛЬНЫЙ ДИРЕКТОР",
            disqualified: null,
          },
          founders: null,
          managers: null,
          predecessors: null,
          successors: null,
          branch_type: "MAIN",
          branch_count: 0,
          source: null,
          qc: null,
          hid: "11fb2cef5967680d0da73657085fc2147643a365c78a53dc3741ed0c6e3ff9c2",
          type: "LEGAL",
          state: {
            status: "ACTIVE",
            code: null,
            actuality_date: 1620345600000,
            registration_date: 1612396800000,
            liquidation_date: null,
          },
          opf: {
            type: "2014",
            code: "12300",
            full: "Общество с ограниченной ответственностью",
            short: "ООО",
          },
          name: {
            full_with_opf:
              'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "ИССЛЕДОВАТЕЛЬСКИЙ ЦЕНТР МОТОРИКА"',
            short_with_opf: 'ООО "ИЦ МОТОРИКА"',
            latin: null,
            full: "ИССЛЕДОВАТЕЛЬСКИЙ ЦЕНТР МОТОРИКА",
            short: "ИЦ МОТОРИКА",
          },
          inn: "9731074967",
          ogrn: "1217700042218",
          okpo: "47067632",
          okato: "45268569000",
          oktmo: "45321000000",
          okogu: "4210011",
          okfs: "34",
          okved: "72.19",
          okveds: null,
          authorities: null,
          documents: null,
          licenses: null,
          finance: null,
          address: {
            value:
              "121205, Г.Москва, ВН.ТЕР.Г. МУНИЦИПАЛЬНЫЙ ОКРУГ МОЖАЙСКИЙ, ТЕР СКОЛКОВО ИННОВАЦИОННОГО ЦЕНТРА, Б-Р БОЛЬШОЙ, Д. 42, СТР. 1, ЭТАЖ/ПОМ/РМ 1/306/09",
            unrestricted_value:
              "121205, Г.Москва, ВН.ТЕР.Г. МУНИЦИПАЛЬНЫЙ ОКРУГ МОЖАЙСКИЙ, ТЕР СКОЛКОВО ИННОВАЦИОННОГО ЦЕНТРА, Б-Р БОЛЬШОЙ, Д. 42, СТР. 1, ЭТАЖ/ПОМ/РМ 1/306/09",
            data: {
              postal_code: "121205",
              country: "Россия",
              country_iso_code: "RU",
              federal_district: "Центральный",
              region_fias_id: "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
              region_kladr_id: "7700000000000",
              region_iso_code: "RU-MOW",
              region_with_type: "г Москва",
              region_type: "г",
              region_type_full: "город",
              region: "Москва",
              area_fias_id: null,
              area_kladr_id: null,
              area_with_type: null,
              area_type: null,
              area_type_full: null,
              area: null,
              city_fias_id: "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
              city_kladr_id: "7700000000000",
              city_with_type: "г Москва",
              city_type: "г",
              city_type_full: "город",
              city: "Москва",
              city_area: "Западный",
              city_district_fias_id: null,
              city_district_kladr_id: null,
              city_district_with_type: "Можайский р-н",
              city_district_type: "р-н",
              city_district_type_full: "район",
              city_district: "Можайский",
              settlement_fias_id: "db22b565-f8ab-464b-b76f-1106629e9e95",
              settlement_kladr_id: "7700000043000",
              settlement_with_type: "тер Сколково инновационного центра",
              settlement_type: "тер",
              settlement_type_full: "территория",
              settlement: "Сколково инновационного центра",
              street_fias_id: "5a08abaa-929f-4855-a460-c691f37b5a25",
              street_kladr_id: "77000000430000400",
              street_with_type: "Большой б-р",
              street_type: "б-р",
              street_type_full: "бульвар",
              street: "Большой",
              stead_fias_id: null,
              stead_cadnum: null,
              stead_type: null,
              stead_type_full: null,
              stead: null,
              house_fias_id: "0519d3e3-d0f6-4106-b1af-c14ddf8f43f5",
              house_kladr_id: "7700000043000040007",
              house_cadnum: null,
              house_type: "д",
              house_type_full: "дом",
              house: "42",
              block_type: "стр",
              block_type_full: "строение",
              block: "1",
              entrance: null,
              floor: null,
              flat_fias_id: null,
              flat_cadnum: null,
              flat_type: null,
              flat_type_full: null,
              flat: null,
              flat_area: null,
              square_meter_price: null,
              flat_price: null,
              postal_box: null,
              fias_id: "0519d3e3-d0f6-4106-b1af-c14ddf8f43f5",
              fias_code: "77000000430000000040007",
              fias_level: "8",
              fias_actuality_state: "0",
              kladr_id: "7700000043000040007",
              geoname_id: "524901",
              capital_marker: "0",
              okato: "45268569000",
              oktmo: "45321000",
              tax_office: "7731",
              tax_office_legal: "7731",
              timezone: "UTC+3",
              geo_lat: "55.6921337",
              geo_lon: "37.3474933",
              beltway_hit: "OUT_MKAD",
              beltway_distance: "4",
              metro: [
                {
                  name: "Сколково",
                  line: "Белорусско-Савеловский",
                  distance: 0.9,
                },
                {
                  name: "Баковка",
                  line: "Белорусско-Савеловский",
                  distance: 2.3,
                },
                {
                  name: "Немчиновка",
                  line: "Белорусско-Савеловский",
                  distance: 3.2,
                },
              ],
              qc_geo: "0",
              qc_complete: null,
              qc_house: null,
              history_values: null,
              unparsed_parts: null,
              source:
                "121205, Г.Москва, ВН.ТЕР.Г. МУНИЦИПАЛЬНЫЙ ОКРУГ МОЖАЙСКИЙ, ТЕР СКОЛКОВО ИННОВАЦИОННОГО ЦЕНТРА, Б-Р БОЛЬШОЙ, Д. 42, СТР. 1, ЭТАЖ/ПОМ/РМ 1/306/09",
              qc: "1",
            },
          },
          phones: null,
          emails: null,
          ogrn_date: 1612396800000,
          okved_type: "2014",
          employee_count: null,
        },
      },
    ];

    const list = this.shadowRoot.querySelector(".suggestions");

    if (results.length > 0 && e.target.value.length > 0) {
      list.style["display"] = "block";
      list.innerHTML = "";
      results.forEach((result) => {
        const el = document.createElement("div");
        el.classList.add("suggestion-item");
        el.innerHTML += `
            <p>${result.value}</p>
        `;
        list.appendChild(el);
      });
    }
    if (e.target.value.length === 0) {
      list.style["display"] = "none";
    }
  }

  connectedCallback() {
    this.shadowRoot
      .querySelector("input")
      .addEventListener("input", (e) => this.fetchSuggestions(e));
  }

  disconnectedCallback() {
    this.shadowRoot.querySelector("input").removeEventListener();
  }
}

window.customElements.define("input-suggestions", InputSuggestions);
